### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by polarathene** [bevacqua/promisees#2]
Tried to view the demo but I'm not seeing any visualization rendered. Others are having similar issues, see: https://www.reddit.com/r/javascript/comments/3lp1a7/javascript_promises_visualization_stepbystep/

**Comment by bevacqua** [comment]
I'll need more info. What browser? Any errors in the console?

**Comment by polarathene** [comment]
I linked to the reddit since there were various browsers/platforms affected. Safari Mobile and Chrome 44 on Windows/OSX. Others will probably chime in on there too.

`VM157:2 Uncaught SyntaxError: missing ) after argument list` is on the console.

**Comment by p3k** [comment]
Same here, Version 44.0.2403.89 Ubuntu 15.04 (64-bit).

**Comment by bevacqua** [comment]
I don't have any issues with Chrome 45. Can you confirm that the issue is some feature of the user code by trying out this url?

http://bevacqua.github.io/promisees/#code=new+Promise(function+(resolve)+%7B%0A++setTimeout(resolve%2C+2000)%0A%7D)

**Comment by p3k** [comment]
This gives me `Uncaught TypeError: z.matrix.findIndex is not a function – demo.min.js:20`.

**Comment by bevacqua** [comment]
Perfect. Needs more polyfills! :)

**Comment by bevacqua** [comment]
Try now. I added a polyfill for `findIndex`. Also please try any ES6 code input after clicking on the Babelify checkbox that I added which compiles code to ES5

**Comment by p3k** [comment]
Works now for me with active Babelify checkbox. Thank you :smile_cat:
