### ISSUE TITLE
Awesome...but also quite confusing to use

### ISSUE THREAD

**Issue by prescod** [bevacqua/promisees#3]
I think that there is a genius idea in here but I find it quite hard to use and understand. The buttons don't have mouseovers to say what they are doing, debugging is very hard, etc.

Does the pulsing indicate how often the code is being run or is it just a visual effect?

What does the recorder button do?

**Comment by bevacqua** [comment]
- Buttons do have mouseovers
- In the case of rejected promises it's jsut a visual effect. Yellow ones are blocked on other promises that haven't settled yet
- It ..records.. a gif of the svg, as seen in the landing page of this repo
