### ISSUE TITLE
"then" not appearing

### ISSUE THREAD

**Issue by dkebler** [bevacqua/promisees#4]
Before I explain my issue just want to put out a big THANKS for this project.  This morning I was frustrated trying to teach myself how to be a good promises coder so I just googled "promises playground" and voila!  I could only go so far reading about promises and bashing my head trying to implement them in a real project.  Your playground makes it easy and visual. Already I'm understanding correct patterns(syntax) better.

So here is some code I put in http://tinyurl.com/jgrm755 that works fine on my local machine but the "then" does not appear in the playground.  

```
function foo(x) {
    done = new Promise( function(resolve,reject){

        setTimeout(function(){
          console.log('Foo is done after',x,' seconds')
          resolve();
          }
        ,x*1000);

    });
    // return a promise
    return done;
}

function bar() {
    console.log('Now doing Bar stuff');
}

function oopsBar() {
    console.log('Something went wrong up before');
}

var p = foo( 5 );

p.then( bar, oopsBar );
```

**Comment by bevacqua** [comment]
Your code is being ran through `babel`, which adds strict mode, which makes the fact that you haven't declared a `done` variable an error. If you either add a `var done` statement up top or you uncheck the babelify option, your code will work properly and the playground will show the `.then` bubble.
